---
- name: 'docker : add apt apt'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: 'docker : add apt repository'
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu disco stable'
    state: present
    update_cache: yes
  become: yes

- name: 'docker : install apt packages'
  apt:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    name: python-docker
  become: yes

- name: 'docker : add {{ username }} to group'
  user:
    name: '{{ username }}'
    groups: docker
    append: yes
  become: yes
