---
- name: 'python : install apt packages'
  apt:
    name: '{{ pkgs }}'
    state: present
  vars:
    pkgs:
      - pipenv
      - python3
      - python3-dev
      - python3-pip
      - python3-pkg-resources
  become: yes
